### PR TITLE
Provisionables are no longer used

### PR DESCRIPTION
**Pull request by calebthompson**
We only need the Provisioners from these gems.

### CODE REVIEW

**Comment by masonforest** [comment]
:+1:

**Comment by chriskacerguis** [comment]
I've asked @jntullo to take a quick look

**Comment by jntullo** [comment]
This will be fine as long as we check actual provisioning. One thing I implemented a while ago in this code was the specs that made sure that provisioning actually functioned properly(https://github.com/projectjellyfish/api/pull/337/files), but then it was removed because of refactor and never put back in. We need to add in something along the lines of what I've done in Azure (although it has to be updated) https://github.com/projectjellyfish/jellyfish-azure/blob/master/spec/models/jellyfish/fog/azure/infrastructure_product_spec.rb to be sure that the order item gets an :ok when it is provisioned. 

Last night's fixes that I put in quickly were just to make sure that provisioning was functioning, but could have been avoided if the specs were put back in.

**Comment by calebthompson** [comment]
> check actual provisioning.

Is there a spec for this now that we can test against? I didn't see any spec changes in your commit from last night. How are you verifying now?

**Comment by jntullo** [comment]
I didn't have time to write the specs. I just went through and tested manually through the UI by creating products, provisioning them, and making sure that they behaved properly (with an ok and received the JSON response)

**Comment by calebthompson** [comment]
This branch actually introduced a failure, which I hadn't had a chance to fix, when combined with the most recent master. I think this is a good example of why it is a better idea for the author of a PR to merge themselves when they know the branch is ready. (And of course why we should have CI setup, which I hadn't gotten around to yet).

It's not the end of the world but that way we have a better assurance that things in master are correct.

**Comment by calebthompson** [comment]
> One thing I implemented a while ago in this code was the specs that made sure that provisioning actually functioned properly(https://github.com/projectjellyfish/api/pull/337/files), but then it was removed because of refactor and never put back in.

[These specs](https://github.com/projectjellyfish/api/pull/337/files#diff-10f901e51200a1dcd699cd12081c120dL1) were kept, but split into multiple files specific to each provisioner subclass. They're in this repo, just need to be run with `rake` during development.

The ones that were removed were testing implementation details. Since we don't care about the return values of what are now private methods, there's no specs there. They're covered by any method that uses them, in this case the `provision` and `retire` methods.

**Comment by calebthompson** [comment]
Though it does appear that `retire` specs were lost.

**Pull request merged**
